#Name: Aaron Cohen
#FSUID: ajc17d
#using the flag -std=c++11 on linprog to access C++11 features

main.o: main.cpp
	clang++  -pedantic -std=c++11 main.cpp -o autocomplete-big-list
autcomplete-3-lists.o: autocomplete-3-lists.cpp
	clang++  -pedantic -std=c++11 autocomplete-3-lists.cpp -o autocomplete-3-lists
clean:
	rm *.o frac
